apiVersion: v1
kind: ReplicationController
metadata:
  name: es-data-$(.group)
  labels:
    component: es-$(.group)
    role: data
spec:
  replicas: $(.data_nodes)
  selector:
    component: es-$(.group)
    role: data
  template:
    metadata:
      labels:
        component: es-$(.group)
        role: data
    spec:
      serviceAccount: es-$(.group)
      containers:
      - name: es-data-$(.group)
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/cafebazaar/elasticsearch-cluster-kubernetes:2.3.1
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: "CLUSTER_NAME"
          value: "myesdb"
        - name: NODE_MASTER
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
