apiVersion: v1
kind: Service
metadata:
  name: es-$(.group)-discovery
  labels:
    component: es-$(.group)
    role: master
spec:
  selector:
    component: es-$(.group)
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
